version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "ivanjojo369"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
    open-pull-requests-limit: 10
    assignees:
      - "ivanjojo369"
    labels:
      - "github-actions"
      - "security"
    commit-message:
      prefix: "ci"
      include: "scope"
      